version: '3.8'

services:
  # Laravel API
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: vibecoding-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - vibecoding-network
    depends_on:
      - db
      - mailhog
      - minio

  # Nginx Web Server
  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: vibecoding-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - vibecoding-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: vibecoding-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-vibecoding}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-vibecoding}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - vibecoding-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vibecoding-network

  # Mailhog for Email Testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: vibecoding-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - vibecoding-network

  # MinIO for Storage
  minio:
    image: minio/minio:latest
    container_name: vibecoding-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    volumes:
      - vibecoding-minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - vibecoding-network

networks:
  vibecoding-network:
    driver: bridge

volumes:
  vibecoding-db-data:
  vibecoding-minio-data:
